### ISSUE TITLE
Aitken transform applied in zeta(2)

### ISSUE THREAD

**Issue by wellington36** [wellington36/extrapolation_methods#1]
With this code:

```python
import math
from acceleration import Aitken_tranform

def square_serie(n: int) -> list:
    serie = [0]

    for i in range(1, n):
        serie.append(serie[-1] + 1/(i)**2)
    
    return serie

if __name__ == "__main__":
    for i in range(1, 6):
        initial_serie = abs(math.pi**2 / 6 - square_serie(10**i)[-1])
        acceration_serie = abs(math.pi**2 / 6 - Aitken_tranform(square_serie(10**i)))

        print(f"Error in initial serie with n={10**i}: {initial_serie}")
        print(f"Errro in acceleration serie with n={10**i}: {acceration_serie}")
        print("\n")
```

We have this output:

``` 
Error in initial serie with n=10: 0.10516633568168565
Errro in acceleration serie with n=10: 0.010476324834324036


Error in initial serie with n=100: 0.010050166663334137
Errro in acceleration serie with n=100: 0.002584953566278081


Error in initial serie with n=1000: 0.0010005001666648639
Errro in acceleration serie with n=1000: 0.001007247008538048


Error in initial serie with n=10000: 0.00010000500016116298
Errro in acceleration serie with n=10000: 0.00010328450128893607


Traceback (most recent call last):
  File "/home/wellington/Documents/acceleration_algorithms/test.py", line 15, in <module>
    acceration_serie = abs(math.pi**2 / 6 - Aitken_tranform(square_serie(10**i)))
  File "/home/wellington/Documents/acceleration_algorithms/acceleration.py", line 11, in Aitken_tranform
    acel.append((items[i] * items[i+2] - items[i+1]**2) / \
ZeroDivisionError: float division by zero
```

We have 2 problems:

- [ ] 1. Division by zero is likely caused by terms that are too close.
- [ ] 2. Initially, the error of the true limit of the accelerated series is much smaller than that of the series without acceleration, however, this distance decreases until the error of the initial one is smaller. This can also be caused by approximation error.

**Comment by wellington36** [comment]
The problem here is the amount of steps solved in the latest version.
